name: Build Windows Executable

on:
  push:
    tags:
      - 'v*'  # Trigger
  workflow_dispatch:  #manual run

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: ğŸ“¥ Checkout repo
        uses: actions/checkout@v4

      - name: ğŸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: ğŸ“¦ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cx_Freeze
          pip install -r requirements.txt

      - name: ğŸ§Š Build executable
        run: python setup.py build

      - name: ğŸ“ Copy build output to dist/
        run: |
          $buildDir = Get-ChildItem -Recurse -Directory -Filter "exe.win-amd64*" | Select-Object -First 1
          mkdir dist
          Copy-Item "$($buildDir.FullName)\*" dist\ -Recurse
        shell: pwsh

      - name: ğŸ—‚ï¸ Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BDIX-TESTER-v0.2.1
          path: dist/
